sudo: required
services:
  - docker

env: # env variables
  global:
    - SHA=$(git rev-parse HEAD) # commit hash
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # disable prompts in travis

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # install Google Cloud SDK
  - source $HOME/google-cloud-sdk/path.bash.inc # install Google Cloud SDK
  - gcloud components update kubectl # install kubectl
  - gcloud auth activate-service-account --key-file service-account.json # auth Google Cloud SDK
  - gcloud config set project multi-k8s-232922 # set project
  - gcloud config set compute/zone us-central1-a # set compute zone
  - gcloud container clusters get-credentials multi-cluster # setup cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # login to docker
  - docker build -t joomrise/react-test -f ./client/Dockerfile.dev ./client # build image

script:
  - docker run joomrise/react-test npm test -- --coverage # run tests

deploy:
  provider: script # deploy is configured from a file
  script: bash ./deploy.sh # deploy script file
  on:
    branch: master # deploy on master branch change
