apiVersion: v1
kind: Service # type of object we want to create. Service will setup networking inside KB cluster
metadata: #id
  name: client-cluster-ip-service
spec:
  type: ClusterIP # the purpose of such type container is to wire up objects inside a cluster, but not expose anything outside
  selector:
      component: web # label selector. "component" part is arbitrary. Can be any other name, but the reference should match.
  ports: # it's an array
    - port: 3000 # port used by other objects to access the Node
      targetPort: 3000 # port open on the Node
