apiVersion: apps/v1
kind: Deployment # legit for both dev & prod.
metadata: # id
  name: postgres-deployment
spec: # spec - desired state
  replicas: 1 # number of pods to be created
  selector: # field defines how the Deployment finds which Pods to manage
    matchLabels:
      component: postgres # look for "postgres" pods (which is defined in template)
  template: # template for pods created by this deployment
    metadata: # pod id
      labels:
        component: postgres
    spec:
      volumes: # requesting for volume defined in "claimName"
        - name: postgres-storage # the name will be requested in volumeMounts
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim # ref
      containers:
        - name: postgres # name of the container
          image: postgres # image to pull. Container will be created out of it.
          ports:
            - containerPort: 5432 # exposed port
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # default storage location for postgres
              subPath: postgres
