apiVersion: apps/v1
kind: Deployment # legit for both dev & prod.
metadata: # id
  name: server-deployment
spec: # spec - desired state
  replicas: 3 # number of pods to be created
  selector: # field defines how the Deployment finds which Pods to manage
    matchLabels:
      component: server # look for "server" pods (which is defined in template)
  template: # template for pods created by this deployment
    metadata: # pod id
      labels:
        component: server
    spec:
      containers:
        - name: server # name of the container
          image: joomrise/multi-server # image to pull. Container will be created out of it.
          ports:
            - containerPort: 5000 # exposed port
          env: # env variables
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: 6379
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: 5432
            - name: PGDATABASE
              value: postgres

